### ISSUE TITLE
Update lodash

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/feathers-client#11]
npm WARN deprecated lodash@2.4.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0.

![screen shot 2015-11-25 at 8 53 51 pm](https://cloud.githubusercontent.com/assets/128857/11414779/c1ea7a3e-93b6-11e5-88be-2b0f008bf20b.jpg)

**Comment by daffl** [comment]
I don't think there is a dependency on Lodash in here at all. I'm wondering if it is because JSHint made it in as an actual not a devDependency at https://github.com/feathersjs/feathers-client/blob/master/package.json#L45.
I added you as a collaborator, would you mind changing it and making a new patch release (after the fix running `npm run release:patch` on master should do it)?

**Comment by marshallswain** [comment]
Yeah.  Thanks.

**Comment by marshallswain** [comment]
Looks like it's feathers-commons: https://github.com/feathersjs/feathers-commons/blob/master/package.json#L47

**Comment by daffl** [comment]
Hm, looking through it I think we can get rid of the dependency completely. It's mainly `_.each` (which could be an easy ES5 helper in `utils.js`), `_.extend` (which is `Object.assign`) and and `_.isArray` (which is provided by `Array.isArray`).

**Comment by marshallswain** [comment]
`dist/` was in the .gitignore, which was causing the release scripts to fail.

**Comment by daffl** [comment]
I think that was fine. We only want to force update `dist/` on a release. I think the missing `prepublish` script I mentioned in #12 is the reason for the missing `lib` folder.
