### ISSUE TITLE
feathers.fetch is undefined

### ISSUE THREAD

**Issue by saiichihashimoto** [feathersjs/feathers-client#27]
Something changed between[v0.5.1 and v0.5.2](https://github.com/feathersjs/feathers-client/compare/v0.5.1...v0.5.2) that made a backwards incompatible change, breaking ```feathers.fetch```. It seems that there have been some changes to how feathers-client works, but using semver means that my application broke when depending on ^0.5.0, though it shouldn't. Not sure if this is a bug or an intentional change. :-)

**Comment by ekryski** [comment]
Sorry that was my bad. I accidentally published it as a patch release.

Yes feathers-client has changed and is now a consolidation wrapper for the other modules. It **will** be following proper semver so the next release will most likely be a 1.0.

We're going to roll out a v0.5.3 that is functionally equivalent to v0.5.1

**Comment by saiichihashimoto** [comment]
Oh exciting, thanks! It looks like you guys are making some changes across the board... anything I should know as a developer who uses feathers? Any "upgrade manual" I should be checking out?

Thanks for the quick reply!

**Comment by ekryski** [comment]
@saiichihashimoto ok v0.5.3 is published. Ya we have a bunch of changes. Feathers 2 is coming out next week! We are working on the migration guide right now. It mostly has to do with how you initialize your database adapters.

Our new docs are still in progress but are getting close to finished docs.feathersjs.com

**Comment by ekryski** [comment]
I think we should be able to close this now then. Let me know if that doesn't work and we can re-open.

**Comment by daffl** [comment]
I'm currently writing the upgrade manual which will live in the guides section of the new docs at http://docs.feathersjs.com/guides/readme.html. Basically `feathers-client` is now literally the same as actual Feathers with some small adapters for establishing client side connection.

The usage from the old version actually shouldn't be too different (instead of `app.configure(feathers.rest(jQuery))` you now do `app.configure(feathers.rest('baseUrl').fetch(fetch)`) but you will also be able to use hooks, client side services and built-in authentication.

**Comment by saiichihashimoto** [comment]
Oh nice, its looks really cool! I'll be excited to use the new stuff. From the documentation, its looking a lot better!
