### ISSUE TITLE
Feathers-client not return correct error object.

### ISSUE THREAD

**Issue by ansarizafar** [feathersjs/feathers-client#44]
I am using feathers-client with ionic2. All services are returning wrong error object without message field. Error messgae field is required for user feedback. I guess that is because of angular2 as If I use angular2 http instead of feathers-client then correct error object is returned from all services. Is it possible to use angular2 Http with feathers client? I am currently using superagent with feathers-client

**Comment by daffl** [comment]
What is it returning? Does this happen with clients other than superagent (if not it might be a bug in the [superagent adapter](https://github.com/feathersjs/feathers-rest/blob/master/src/client/superagent.js))?

Of course you can use the HTTP methods directly (see http://docs.feathersjs.com/clients/vanilla-rest.html). We usually recommend [using websockets](http://docs.feathersjs.com/clients/socket-io.html) instead of the REST clients however so you also get the advantage of Feathers [real-time](http://docs.feathersjs.com/real-time/readme.html) capabilities.

**Comment by daffl** [comment]
I'm going to close this. Please reopen if you can provide more information.
