### ISSUE TITLE
[Question] Large client-side bundle filesize when requiring feathers client

### ISSUE THREAD

**Issue by petermikitsh** [feathersjs/feathers-client#71]
Hi Feathers team,

When adding the following lines to my project, my webpack `bundle.js` file grows from `629 kB` to `2.06 MB`.

```js
const feathers = require('feathers/client');
const rest = require('feathers-rest/client');
const superagent = require('superagent');
const app = feathers().configure(
  rest(__API__).superagent(superagent)
);
```

Superagent is ~20kb (upon comparison webpack builds with and without it), so I suspect the majority of the increase is due to `feathers` and `feathers-rest`. Is there anyway (1) I can optimize Webpack to reduce my bundle filesize or (2) code changes to feathers to export less stuff?

**Comment by daffl** [comment]
The [Browserified feathers-client](https://github.com/feathersjs/feathers-client/tree/master/dist) is about 17k minified + gzipped.

The issue is probably `babel-polyfill` not mapped to an empty module (see https://github.com/feathersjs/feathers-client/blob/master/package.json#L48 - although I thought Webpack recognizes the `browser` field) and then including your own ES6 polyfill (a `babel-polyfill browser build or the `core-js` main distributable).

Another problem might be including `feathers` instead of `feathers/client` somewhere which will try to bundle browser builds for everything that comes with Express.

**Comment by petermikitsh** [comment]
It appears to be an issue with my configuration. A sandboxed webpack build produces expected results (`52.3kb`) -- see [petermikitsh/feathers-client-filesize](https://github.com/petermikitsh/feathers-client-filesize).

```
$ npm run build

> feathers-client-filesize@0.0.0 build /Users/pmikitsh/git/feathers-client-filesize
> webpack --config ./webpack.js

Hash: 71a7163aa1c3777646da
Version: webpack 1.13.1
Time: 1143ms
        Asset       Size  Chunks             Chunk Names
    bundle.js    53.2 kB       0  [emitted]  main
bundle.js.map  122 bytes       0  [emitted]  main
 bundle.js.gz    14.1 kB          [emitted]  
   [0] multi main 28 bytes {0} [built]
    + 38 hidden modules
```

I'll report back if I find a solution for my actual project's configuration.

**Comment by petermikitsh** [comment]
Renaming my webpack DefinePlugin variable from `__API__` to `API` solved the problem. I have no idea why, but I'll be happy and accept this black magic.

With React + Redux + Feathers + Lots of other fun things, new webpack build size is `682 kB`, and gzipped `160 kB`.

🎉
